import { type FormEvent, type ReactNode, useState } from 'react';
import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { Brand, Button } from '@/components/athlete-ui';

export function Login() {
  const [, setLocation] = useLocation();
  const [showPassword, setShowPassword] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLocation('/dashboard'); };
  return <AuthFrame eyebrow="Welcome back" title={<>Back to<br /><span>work.</span></>} copy="Your next chapter is waiting. Pick up where you left off."><form onSubmit={submit} className="mt-8 space-y-4"><Field label="Email" icon={Mail} type="email" autoComplete="email" placeholder="you@email.com" id="input-email" required /><Field label="Password" icon={LockKeyhole} type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="Your password" id="input-password" required end={<button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'} data-testid="button-toggle-password">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button>} /><Button type="submit" className="mt-3 w-full py-3.5" data-testid="button-log-in">Log In <ArrowRight size={17} /></Button><p className="text-center text-sm text-[hsl(var(--muted-foreground))]">New to Athlete Hub? <Link href="/signup" className="font-bold text-[hsl(var(--primary))]" data-testid="link-continue-signup">Continue to Sign Up</Link></p></form></AuthFrame>;
}

export function Signup() {
  const [, setLocation] = useLocation();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLocation('/dashboard'); };
  return <AuthFrame eyebrow="Build your identity" title={<>Make your<br /><span>mark.</span></>} copy="Start with the player you are. Grow into the one you are becoming."><form onSubmit={submit} className="mt-8 space-y-3"><Field label="Display name" icon={UserRound} autoComplete="name" placeholder="Jordan Lincoln" id="input-display-name" required /><Field label="Username" icon={UserRound} autoComplete="username" placeholder="jlincoln" id="input-username" required /><Field label="Email" icon={Mail} type="email" autoComplete="email" placeholder="you@email.com" id="input-signup-email" required /><Field label="Password" icon={LockKeyhole} type="password" autoComplete="new-password" placeholder="At least 8 characters" id="input-signup-password" minLength={8} required /><Button type="submit" className="mt-3 w-full py-3.5" data-testid="button-create-player-submit">Create Player <ArrowRight size={17} /></Button><p className="text-center text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">By creating a player, you agree to keep showing up for the work.</p></form></AuthFrame>;
}

function Field({ label, icon: Icon, id, end, ...props }: { label: string; icon: typeof Mail; id: string; end?: ReactNode; [key: string]: unknown }) {
  return <label className="block text-left"><span className="mb-1.5 block font-mono text-[10px] uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]">{label}</span><span className="flex items-center gap-3 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-3 transition-colors focus-within:border-[hsl(var(--primary))]"><Icon size={17} className="text-[hsl(var(--muted-foreground))]" /><input {...props} id={id} data-testid={id} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[hsl(var(--muted-foreground))]/65" />{end}</span></label>;
}

function AuthFrame({ eyebrow, title, copy, children }: { eyebrow: string; title: ReactNode; copy: string; children: ReactNode }) {
  return <div className="site-noise grid min-h-[100dvh] bg-[hsl(var(--background))] lg:grid-cols-[.85fr_1.15fr]"><div className="relative hidden overflow-hidden bg-[hsl(var(--secondary))] p-10 text-[hsl(var(--secondary-foreground))] lg:block"><div className="absolute inset-0 court-lines opacity-25" /><div className="absolute -bottom-40 -left-20 h-[32rem] w-[32rem] rounded-full border border-white/10" /><div className="absolute -bottom-20 -left-4 h-60 w-60 rounded-full border border-white/10" /><Brand light /><div className="absolute bottom-14 left-10 right-10"><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--accent))]">Player identity, unlocked</p><p className="mt-4 max-w-sm font-display text-6xl font-black uppercase leading-[.85]">The work<br />has a<br /><span className="text-[hsl(var(--primary))]">place.</span></p></div></div><div className="flex flex-col px-5 py-6 sm:px-10 lg:px-20 lg:py-10"><Link href="/" className="mb-14 inline-flex w-fit items-center gap-2 text-sm font-bold text-[hsl(var(--muted-foreground))]" data-testid="link-back-home"><ArrowLeft size={16} /> Back home</Link><div className="my-auto w-full max-w-md"><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">{eyebrow}</p><h1 className="mt-3 font-display text-7xl font-black uppercase leading-[.82]">{title}</h1><p className="mt-5 max-w-sm text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{copy}</p>{children}</div><p className="mt-12 font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">ATHLETE / HUB · 2024—25</p></div></div>;
}