import { ArrowUpRight, CalendarDays, ChevronRight, Flame, Gamepad2, MoreHorizontal, Plus, Trophy } from 'lucide-react';
import { Link } from 'wouter';
import { useState } from 'react';
import { achievements, player, recentGame } from '@/data/mock-data';
import { AchievementCard, AppShell, Button, PlayerCard, StatCard, XPProgress } from '@/components/athlete-ui';

export default function Dashboard() {
  const [notice, setNotice] = useState('');
  return <AppShell><div className="mx-auto max-w-7xl px-5 py-7 md:px-10 md:py-10"><header className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">Thursday, November 21</p><h1 className="mt-2 font-display text-5xl font-black uppercase leading-none sm:text-6xl">Good to see you,<br /><span className="text-[hsl(var(--primary))]">{player.firstName}.</span></h1></div><div className="hidden items-center gap-3 sm:flex"><span className="rounded-full border border-[hsl(var(--border))] px-3 py-2 font-mono text-[10px] text-[hsl(var(--muted-foreground))]">{player.season}</span><div className="grid h-10 w-10 place-items-center rounded-full bg-[hsl(var(--accent))] text-sm font-black">JL</div></div></header>
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl bg-[hsl(var(--secondary))] p-5 text-[hsl(var(--secondary-foreground))] sm:p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-white/50">Your player rating</p><div className="mt-2 flex items-end gap-3"><span className="font-display text-8xl font-black leading-[.75] text-[hsl(var(--accent))]">{player.ovr}</span><div className="mb-1"><p className="font-display text-3xl font-bold uppercase">OVR</p><p className="text-xs text-white/55">{player.position} · {player.team}</p></div></div></div><div className="flex items-center gap-1 rounded bg-[hsl(var(--primary))] px-2 py-1 font-mono text-[10px] font-bold"><ArrowUpRight size={13} /> +6</div></div><div className="mt-9 grid max-w-lg grid-cols-3 gap-2 border-t border-white/10 pt-4">{[['14.2','PPG'],['4.8','RPG'],['5.1','APG']].map(([value, label]) => <div key={label}><p className="font-display text-3xl font-bold">{value}</p><p className="font-mono text-[9px] uppercase tracking-widest text-white/45">{label}</p></div>)}</div></section><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Season progress</p><p className="mt-2 font-display text-4xl font-black uppercase">Keep climbing.</p></div><Flame className="text-[hsl(var(--primary))]" size={23} /></div><div className="mt-8"><XPProgress /></div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Last game</p><h2 className="mt-1 font-display text-3xl font-bold uppercase">{recentGame.opponent}</h2></div><button onClick={() => setNotice('Game details are already up to date.')} className="rounded-lg p-2 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]" aria-label="More game options" data-testid="button-game-options"><MoreHorizontal size={20} /></button></div><div className="mt-1 flex items-center gap-2 text-xs text-[hsl(var(--muted-foreground))]"><CalendarDays size={13} />{recentGame.date}<span className="font-bold text-[hsl(var(--primary))]">{recentGame.result}</span></div><div className="mt-7 grid grid-cols-4 gap-2">{[['18','PTS'],['7','REB'],['6','AST'],['2','STL']].map(([value, label]) => <div key={label} className="rounded-lg bg-[hsl(var(--muted))] p-3"><p className="font-display text-3xl font-black">{value}</p><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">{label}</p></div>)}</div><Link href="/dashboard" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-view-game">View game details <ChevronRight size={14} /></Link></section><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Your collection</p><p className="mt-1 font-display text-3xl font-bold uppercase">Career cards</p></div><Trophy size={22} className="text-[hsl(var(--accent-foreground))] fill-[hsl(var(--accent))]" /></div><div className="mt-6 flex items-end justify-between"><p className="font-display text-6xl font-black">18<span className="text-2xl text-[hsl(var(--muted-foreground))]"> / 100</span></p><Link href="/collection" className="rounded-lg bg-[hsl(var(--muted))] p-2 hover:bg-[hsl(var(--accent))]" aria-label="Open collection" data-testid="link-open-collection"><ChevronRight size={18} /></Link></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="h-full w-[18%] rounded-full bg-[hsl(var(--accent))]" /></div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Milestones</p><h2 className="mt-1 font-display text-3xl font-bold uppercase">Earned this season</h2></div><Link href="/profile" className="text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-all-achievements">View all</Link></div><div className="grid gap-3 sm:grid-cols-2">{achievements.slice(0, 2).map(item => <AchievementCard key={item.id} item={item} />)}</div></section><section className="grid grid-cols-2 gap-3"><StatCard label="Games" value={String(player.games)} sub="this season" icon={Gamepad2} /><StatCard label="Best run" value="3W" sub="current streak" icon={Flame} /></section></div>
    {notice && <button onClick={() => setNotice('')} className="fixed bottom-[145px] right-5 z-20 rounded-lg bg-[hsl(var(--secondary))] px-4 py-3 text-xs font-bold text-[hsl(var(--secondary-foreground))] shadow-lg" data-testid="button-dismiss-notice">{notice}</button>}
    <Button variant="dark" onClick={() => setNotice('Game logging will be available in your next session.')} className="fixed bottom-[88px] right-5 z-10 rounded-full px-4 py-3 lg:bottom-8" data-testid="button-add-game"><Plus size={17} /> Log a game</Button>
  </div></AppShell>;
}