import { ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, Flame, Gamepad2, MoreHorizontal, Plus, Trophy } from 'lucide-react';
import { Link } from 'wouter'; from 'wouter';
import { useState } from 'react';
import { achievements, leaderboard, player, recentGame } from '@/data/mock-data';
import { AchievementCard, AppShell, Button, LeaderboardRow, PlayerCard, ProUpgradeCard, StatCard, XPProgress } from '@/components/athlete-ui';

export default function Dashboard() {
  const [notice, setNotice] = useState('');
  return <AppShell><div className="atmosphere min-h-[calc(100dvh-1px)]"><div className="mx-auto max-w-7xl px-5 py-7 md:px-10 md:py-10">
    <header className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">Preview dashboard · Thursday, March 12</p><h1 className="mt-2 font-display text-5xl font-black uppercase leading-none sm:text-6xl">Good to see you,<br /><span className="text-gradient">{player.firstName}.</span></h1></div><div className="hidden items-center gap-3 sm:flex"><span className="rounded-full border border-[hsl(var(--border))] px-3 py-2 font-mono text-[10px] text-[hsl(var(--muted-foreground))]">SEASON {player.season}</span><div className="grid h-10 w-10 place-items-center rounded-full bg-[hsl(var(--primary))] text-sm font-black text-[hsl(var(--primary-foreground))]">JL</div></div></header>
    <div className="mt-8 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><div className="flex justify-center rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--secondary))]/60 p-5 sm:p-7 xl:justify-start"><PlayerCard /></div><div className="grid gap-5"><section className="surface-elevated rounded-2xl border border-[hsl(var(--primary))]/25 p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Your player rating · mock</p><div className="mt-2 flex items-end gap-3"><span className="animate-number font-display text-8xl font-black leading-[.75] text-[hsl(var(--accent))]">{player.ovr}</span><div className="mb-1"><p className="font-display text-3xl font-bold uppercase">OVR</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{player.position} · {player.team}</p><p className="mt-1 flex items-center gap-1 text-[10px] font-bold text-[hsl(var(--success))]"><ArrowUpRight size={12} /> +6 this season</p></div></div></div><div className="flex items-center gap-1 rounded bg-[hsl(var(--accent))]/15 px-2 py-1 font-mono text-[10px] font-bold text-[hsl(var(--accent))]">★★★★ EST.</div></div><div className="mt-9 grid max-w-lg grid-cols-4 gap-2 border-t border-[hsl(var(--border))] pt-4">{[[player.ppg, 'PPG'], [player.rpg, 'RPG'], [player.apg, 'APG'], [player.fg, 'FG']].map(([value, label]) => <div key={label}><p className="font-display text-3xl font-bold">{value}</p><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">{label}</p></div>)}</div></section><section className="surface-elevated rounded-2xl border border-[hsl(var(--border))] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Season progression · mock</p><p className="mt-2 font-display text-4xl font-black uppercase">Keep climbing.</p></div><Flame className="text-[hsl(var(--highlight))]" size={23} /></div><div className="mt-7"><XPProgress /></div></section></div></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><section className="surface-elevated rounded-2xl border border-[hsl(var(--border))] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Recent performance · mock</p><h2 className="mt-1 font-display text-3xl font-bold uppercase">{recentGame.opponent}</h2></div><button onClick={() => setNotice('Game details are preview data for now.')} className="rounded-lg p-2 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]" aria-label="More game options" data-testid="button-game-options"><MoreHorizontal size={20} /></button></div><div className="mt-1 flex items-center gap-2 text-xs text-[hsl(var(--muted-foreground))]"><CalendarDays size={13} />{recentGame.date}<span className="font-bold text-[hsl(var(--success))]">{recentGame.result}</span></div><div className="mt-7 grid grid-cols-4 gap-2">{[['18', 'PTS'], ['7', 'REB'], ['6', 'AST'], ['2', 'STL']].map(([value, label]) => <div key={label} className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--muted))]/60 p-3"><p className="font-display text-3xl font-black">{value}</p><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">{label}</p></div>)}</div><Link href="/dashboard" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-view-game">View game details <ChevronRight size={14} /></Link></section><section className="surface-elevated rounded-2xl border border-[hsl(var(--border))] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Your collection</p><p className="mt-1 font-display text-3xl font-bold uppercase">Career cards</p></div><Trophy size={22} className="fill-[hsl(var(--accent))] text-[hsl(var(--accent))]" /></div><div className="mt-6 flex items-end justify-between"><p className="font-display text-6xl font-black">{player.collectionCount}<span className="text-2xl text-[hsl(var(--muted-foreground))]"> / 100</span></p><Link href="/collection" className="rounded-lg bg-[hsl(var(--muted))] p-2 hover:bg-[hsl(var(--accent))]" aria-label="Open collection" data-testid="link-open-collection"><ChevronRight size={18} /></Link></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="animate-progress h-full rounded-full bg-[linear-gradient(90deg,hsl(var(--primary)),hsl(var(--secondary-accent)))]" style={{ width: `${player.collectionCount}%` }} /></div><p className="mt-2 font-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Preview collection progress</p></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="surface-elevated rounded-2xl border border-[hsl(var(--border))] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Milestones · mock</p><h2 className="mt-1 font-display text-3xl font-bold uppercase">Earned this season</h2></div><Link href="/profile" className="text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-all-achievements">View all</Link></div><div className="grid gap-3 sm:grid-cols-2">{achievements.slice(0, 2).map(item => <AchievementCard key={item.id} item={item} />)}</div></section><section className="grid grid-cols-2 gap-3"><StatCard label="Games" value={String(player.games)} sub="preview season" icon={Gamepad2} /><StatCard label="Best run" value="3W" sub="mock streak" icon={Flame} /></section></div>
    <section className="mt-5 surface-elevated rounded-2xl border border-[hsl(var(--border))] p-5 sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">Competitive preview</p><h2 className="mt-1 font-display text-3xl font-bold uppercase">Leaderboard position</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Fictional rankings while the competitive layer is in development.</p></div><Link href="/leaderboard" className="inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))]">View full leaderboard <ChevronRight size={14} /></Link></div><div className="animate-stagger mt-5 grid gap-2">{leaderboard.slice(0, 3).map(entry => <LeaderboardRow key={entry.rank} entry={entry} />)}<LeaderboardRow entry={leaderboard[3]} /></div></section>
    <div className="mt-5"><ProUpgradeCard compact /></div>
    {notice && <button onClick={() => setNotice('')} className="fixed bottom-[145px] right-5 z-20 rounded-lg bg-[hsl(var(--secondary))] px-4 py-3 text-xs font-bold text-[hsl(var(--secondary-foreground))] shadow-lg" data-testid="button-dismiss-notice">{notice}</button>}
    <Link href="/log-game" className="fixed bottom-[88px] right-5 z-10 rounded-full px-4 py-3 lg:bottom-8"><Button variant="primary"><Plus size={17} /> Log a game</Button></Link>
  </div></div></AppShell>;
}