import { ArrowDown, ArrowRight, BarChart3, Check, ChevronRight, Medal, Sparkles, Target, Trophy } from 'lucide-react';
import { Link } from 'wouter';
import { Brand, Button, CollectionCard, PackPreview, PlayerCard, ProUpgradeCard } from '@/components/athlete-ui';
import { cards, player } from '@/data/mock-data';

const pillars = [
  { icon: BarChart3, number: '01', title: 'Track your game', text: 'Log games and build the real basketball statistics behind your story.' },
  { icon: Target, number: '02', title: 'Build your OVR', text: 'Turn your performance into an evolving player rating that moves with you.' },
  { icon: Sparkles, number: '03', title: 'Level up', text: 'Earn XP, achievements, and milestones for the work nobody else sees.' },
  { icon: Medal, number: '04', title: 'Compete + collect', text: 'Climb the preview leaderboard and collect cards from your basketball journey.' },
];

export default function Landing() {
  return <div className="site-noise atmosphere min-h-[100dvh] overflow-hidden">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><Brand /><div className="flex items-center gap-3"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-bold text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))]" data-testid="link-login">Log in</Link><Link href="/signup" className="hidden sm:inline-flex"><Button data-testid="button-header-create">Create your player <ArrowRight size={16} /></Button></Link></div></header>
    <main>
      <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-12 md:grid-cols-[1.05fr_.95fr] md:px-10 md:pb-36 md:pt-20">
        <div className="absolute -left-40 top-10 h-80 w-80 rounded-full bg-[hsl(var(--primary))]/15 blur-3xl" /><div className="absolute right-0 top-1/3 h-72 w-72 rounded-full bg-[hsl(var(--secondary-accent))]/10 blur-3xl" />
        <div className="relative z-10 animate-rise"><div className="mb-6 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.24em] text-[hsl(var(--primary))]"><span className="h-2 w-2 rounded-full bg-[hsl(var(--primary))] shadow-[0_0_14px_hsl(var(--primary))]" /> Your career, in play</div><h1 className="text-balance font-display text-[clamp(4.1rem,11vw,8.8rem)] font-black uppercase leading-[.8] tracking-[-.04em] text-[hsl(var(--foreground))]">Turn your<br /><span className="text-gradient">basketball</span><br />journey into<br />a career.</h1><p className="mt-8 max-w-lg text-base leading-relaxed text-[hsl(var(--muted-foreground))] md:text-lg">Athlete Hub lets basketball players track their game, build their player profile, level up, compete, and collect cards representing their basketball journey.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/signup"><Button className="px-5 py-3.5" data-testid="button-create-player">Create Your Player <ArrowRight size={17} /></Button></Link><a href="#how-it-works" className="group inline-flex items-center gap-2 rounded-lg px-3 py-3 text-sm font-bold text-[hsl(var(--foreground))]" data-testid="link-how-it-works">See How It Works <ArrowDown size={16} className="transition-transform group-hover:translate-y-1" /></a></div><div className="mt-9 flex items-center gap-3 font-mono text-[9px] uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]"><span className="rounded-full border border-[hsl(var(--border))] px-3 py-1.5">Preview build</span><span>Made for the work behind the highlight</span></div></div>
        <div className="relative z-10 flex justify-center animate-rise-delay md:justify-end"><div className="absolute right-0 top-0 h-44 w-44 rounded-full border border-[hsl(var(--primary))]/25 md:right-10" /><div className="absolute -bottom-4 left-4 -z-10 h-52 w-52 rounded-full bg-[hsl(var(--secondary-accent))]/15 blur-2xl" /><div className="card-tilt"><PlayerCard /></div><div className="absolute -bottom-5 left-0 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]/95 p-3 shadow-2xl backdrop-blur sm:left-5"><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Current OVR</p><div className="flex items-baseline gap-2"><span className="font-display text-4xl font-black text-[hsl(var(--foreground))]">78</span><span className="text-xs font-bold text-[hsl(var(--success))]">+06 this season</span></div></div></div>
      </section>
      <section id="how-it-works" className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary))]/75 px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">The core loop</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.9] text-[hsl(var(--foreground))] md:text-7xl">Make progress<br /><span className="text-gradient">visible.</span></h2></div><div className="mt-14 grid gap-3 md:grid-cols-4">{pillars.map(({ icon: Icon, title, text, number }) => <article key={title} className="group surface-elevated rounded-2xl border border-[hsl(var(--border))] p-6 transition-transform duration-300 hover:-translate-y-1 hover:border-[hsl(var(--primary))]/40"><div className="mb-12 flex h-10 w-10 items-center justify-center rounded-lg bg-[hsl(var(--primary))]/12 text-[hsl(var(--primary))] transition-transform group-hover:rotate-6"><Icon size={19} /></div><p className="font-mono text-[10px] text-[hsl(var(--muted-foreground))]">{number}</p><h3 className="mt-2 font-display text-3xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{text}</p></article>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 md:px-10 md:py-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">Your career, collected</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.88] md:text-7xl">Your career.<br /><span className="text-gradient">Collected.</span></h2></div><p className="max-w-sm text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Seasons, achievements, milestones, performances, and special moments — each one becomes a piece of your story. These are visual previews only.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4">{cards.filter(card => ['Common', 'Rare', 'Epic', 'Legendary'].includes(card.rarity)).map(card => <CollectionCard key={card.id} card={card} />)}</div><div className="mt-5 flex items-center justify-between rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]/60 px-4 py-3"><p className="font-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Collection preview · {player.collectionCount} / 100 cards</p><Link href="/collection" className="inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))]">View collection <ChevronRight size={14} /></Link></div></section>
      <section className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary))]/60 px-5 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--secondary-accent))]">The next reveal</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.88]">Reward the<br /><span className="text-gradient">work.</span></h2><p className="mt-6 max-w-sm text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">A future pack-opening experience turns earned moments into collectible reveals. No purchases, no monetary value — just a playful preview of what is ahead.</p></div><PackPreview /></div></section>
      <section className="mx-auto grid max-w-7xl gap-8 px-5 py-20 md:px-10 md:py-28 lg:grid-cols-[.82fr_1.18fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">Built to grow with you</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.88] md:text-7xl">The work<br />has a<br /><span className="text-gradient">place.</span></h2><p className="mt-6 max-w-sm text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Start free with a player profile, basic progress, achievements, cards, and leaderboard participation. Athlete Hub Pro is a clearly labeled future layer — not a paywall on the work.</p><div className="mt-7 flex items-center gap-3 text-sm font-bold"><Check className="text-[hsl(var(--success))]" size={17} /> Free means useful from day one</div><div className="mt-2 flex items-center gap-3 text-sm font-bold"><Check className="text-[hsl(var(--success))]" size={17} /> Pro features are coming soon</div></div><ProUpgradeCard /></section>
      <section className="bg-[hsl(var(--secondary))] px-5 py-20 text-[hsl(var(--secondary-foreground))] md:px-10 md:py-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--accent))]">Next possession</p><h2 className="mt-3 max-w-2xl font-display text-6xl font-black uppercase leading-[.82] md:text-8xl">Your name.<br /><span className="text-[hsl(var(--primary))]">Your game.</span></h2></div><Link href="/signup"><Button variant="primary" className="shrink-0" data-testid="button-closing-cta">Create your player <ArrowRight size={17} /></Button></Link></div></section>
    </main>
    <footer className="flex flex-col gap-2 px-5 py-6 text-xs text-[hsl(var(--muted-foreground))] sm:flex-row sm:items-center sm:justify-between md:px-10"><Brand /><span>Built for the work behind the highlight.</span></footer>
  </div>;
}