import { ArrowDown, ArrowRight, BarChart3, Check, ChevronRight, Medal, Sparkles, Target, Trophy } from 'lucide-react';
import { Link } from 'wouter';
import { Brand, Button, PlayerCard } from '@/components/athlete-ui';

export default function Landing() {
  return <div className="site-noise min-h-[100dvh] overflow-hidden bg-[hsl(var(--background))]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><Brand /><div className="flex items-center gap-3"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-bold hover:bg-[hsl(var(--muted))]" data-testid="link-login">Log in</Link><Link href="/signup" className="hidden sm:inline-flex"><Button data-testid="button-header-create">Create your player <ArrowRight size={16} /></Button></Link></div></header>
    <main>
      <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-12 md:grid-cols-[1.05fr_.95fr] md:px-10 md:pb-32 md:pt-20">
        <div className="absolute -left-40 top-10 -z-0 h-80 w-80 rounded-full bg-[hsl(var(--accent))]/30 blur-3xl" />
        <div className="relative z-10 animate-rise"><div className="mb-6 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.24em] text-[hsl(var(--primary))]"><span className="h-2 w-2 rounded-full bg-[hsl(var(--primary))]" /> Your career, in play</div><h1 className="text-balance font-display text-[clamp(4.1rem,11vw,8.8rem)] font-black uppercase leading-[.82] tracking-[-.04em] text-[hsl(var(--secondary))]">Turn your<br /><span className="text-[hsl(var(--primary))]">basketball</span><br />journey into<br />a career.</h1><p className="mt-8 max-w-md text-base leading-relaxed text-[hsl(var(--muted-foreground))] md:text-lg">Athlete Hub gives every rep a record, every milestone a moment, and every player a profile worth remembering.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/signup"><Button className="px-5 py-3.5" data-testid="button-create-player">Create Your Player <ArrowRight size={17} /></Button></Link><a href="#how-it-works" className="group inline-flex items-center gap-2 rounded-lg px-3 py-3 text-sm font-bold" data-testid="link-how-it-works">See How It Works <ArrowDown size={16} className="transition-transform group-hover:translate-y-1" /></a></div></div>
        <div className="relative z-10 flex justify-center animate-rise-delay md:justify-end"><div className="absolute right-4 top-0 h-36 w-36 rounded-full border border-[hsl(var(--primary))]/30 md:right-10" /><div className="absolute -bottom-4 left-4 -z-10 h-48 w-48 rounded-full bg-[hsl(var(--primary))]/20 blur-2xl" /><div className="rotate-3 transition-transform duration-500 hover:rotate-0"><PlayerCard /></div><div className="absolute -bottom-4 left-0 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3 shadow-lg sm:left-5"><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Current OVR</p><div className="flex items-baseline gap-2"><span className="font-display text-4xl font-black">78</span><span className="text-xs font-bold text-[hsl(var(--primary))]">+06 this season</span></div></div></div>
      </section>
      <section id="how-it-works" className="border-y border-[hsl(var(--border))] bg-[hsl(var(--card))] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">More than a stat sheet</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.9] md:text-7xl">Make progress<br /><span className="text-[hsl(var(--primary))]">visible.</span></h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--border))] md:grid-cols-4">
          {[{ icon: BarChart3, title: 'Track the work', text: 'Log games, see your trends, and know what is moving your game forward.' }, { icon: Target, title: 'Build your OVR', text: 'Turn consistent performance into a player rating that tells the whole story.' }, { icon: Sparkles, title: 'Collect your career', text: 'Every season becomes a card. Keep the moments that made you.' }, { icon: Medal, title: 'Earn the moments', text: 'Unlock achievements for the plays, runs, and habits you will never forget.' }].map(({ icon: Icon, title, text }, i) => <article key={title} className={`bg-[hsl(var(--card))] p-6 ${i === 0 ? 'md:rounded-l-2xl' : ''}`}><div className="mb-12 flex h-10 w-10 items-center justify-center rounded-lg bg-[hsl(var(--accent))] text-[hsl(var(--accent-foreground))]"><Icon size={19} /></div><p className="font-mono text-[10px] text-[hsl(var(--muted-foreground))]">0{i + 1}</p><h3 className="mt-2 font-display text-3xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{text}</p></article>)}
        </div></div></section>
      <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-[.75fr_1.25fr] md:px-10 md:py-28"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--primary))]">Your identity, in full</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.88] md:text-7xl">Every<br />game tells<br /><span className="text-[hsl(var(--primary))]">a story.</span></h2><p className="mt-6 max-w-sm text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Not just points. The big run. The tough loss. The summer that changed your shot. Athlete Hub keeps the receipts.</p><Link href="/signup" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-start-story">Start your story <ChevronRight size={16} /></Link></div><div className="relative grid grid-cols-2 gap-3 sm:gap-5"><div className="mt-12 rounded-2xl bg-[hsl(var(--secondary))] p-5 text-[hsl(var(--secondary-foreground))] sm:p-8"><Trophy className="text-[hsl(var(--accent))]" size={25} /><p className="mt-14 font-mono text-[10px] uppercase tracking-widest text-white/50">Career highlights</p><p className="mt-2 font-display text-4xl font-black sm:text-6xl">23</p><p className="text-sm text-white/60">games logged</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-8"><Check className="text-[hsl(var(--primary))]" size={25} /><p className="mt-14 font-mono text-[10px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Achievements</p><p className="mt-2 font-display text-4xl font-black sm:text-6xl">12</p><p className="text-sm text-[hsl(var(--muted-foreground))]">earned so far</p></div></div></section>
      <section className="bg-[hsl(var(--secondary))] px-5 py-20 text-[hsl(var(--secondary-foreground))] md:px-10 md:py-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-[hsl(var(--accent))]">Next possession</p><h2 className="mt-3 max-w-2xl font-display text-6xl font-black uppercase leading-[.82] md:text-8xl">Your name.<br /><span className="text-[hsl(var(--primary))]">Your game.</span></h2></div><Link href="/signup"><Button variant="primary" className="shrink-0" data-testid="button-closing-cta">Create your player <ArrowRight size={17} /></Button></Link></div></section>
    </main>
    <footer className="flex flex-col gap-2 px-5 py-6 text-xs text-[hsl(var(--muted-foreground))] sm:flex-row sm:items-center sm:justify-between md:px-10"><Brand /><span>Built for the work behind the highlight.</span></footer>
  </div>;
}