import { ArrowRight, ChevronDown, Filter, Sparkles, Trophy, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { useState } from 'react';
import { leaderboard, player } from '@/data/mock-data';
import { AppShell, Button, LeaderboardRow } from '@/components/athlete-ui';

const tabs = ['Global', 'Local', 'School', 'Friends'] as const;
const sorts = ['OVR', 'XP', 'PPG', 'APG', 'RPG'] as const;

export default function Leaderboard() {
  const [activeTab, setActiveTab] = useState<(typeof tabs)[number]>('Global');
  const [sort, setSort] = useState<(typeof sorts)[number]>('OVR');
  const [sortOpen, setSortOpen] = useState(false);
  return <AppShell><div className="atmosphere min-h-[calc(100dvh-1px)]"><div className="mx-auto max-w-7xl px-5 py-7 md:px-10 md:py-10">
    <header className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.22em] text-[hsl(var(--primary))]"><UsersRound size={13} /> Preview leaderboard</div><h1 className="mt-3 font-display text-6xl font-black uppercase leading-[.82] sm:text-8xl">Climb the<br /><span className="text-gradient">ranks.</span></h1><p className="mt-5 max-w-md text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">A fictional snapshot of the Athlete Hub competitive layer. Everyone here is mock data while the real leaderboard is still in development.</p></div><div className="surface-elevated rounded-2xl border border-[hsl(var(--primary))]/25 p-5 sm:min-w-[260px]"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Your next rank</p><p className="mt-2 font-display text-5xl font-black text-[hsl(var(--accent))]">12 OVR</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">away from #3 · Alex R.</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="h-full w-[68%] rounded-full bg-[linear-gradient(90deg,hsl(var(--primary)),hsl(var(--secondary-accent)))]" /></div></div></header>
    <section className="mt-10 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]/75 p-4 sm:p-6" data-testid="leaderboard-panel"><div className="flex flex-col gap-4 border-b border-[hsl(var(--border))] pb-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2 overflow-x-auto pb-1">{tabs.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold transition-colors ${activeTab === tab ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]'}`} data-testid={`button-leaderboard-tab-${tab.toLowerCase()}`}>{tab}{tab !== 'Global' && <span className="ml-1.5 font-mono text-[9px] opacity-70">Preview</span>}</button>)}</div><div className="relative flex items-center gap-2 self-start lg:self-auto"><span className="font-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Sort</span><button onClick={() => setSortOpen(!sortOpen)} className="inline-flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] px-3 py-2 text-xs font-bold" data-testid="button-leaderboard-sort"><Filter size={13} /> {sort} <ChevronDown size={13} /></button>{sortOpen && <div className="absolute right-0 top-full z-10 mt-2 min-w-28 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-1 shadow-xl">{sorts.map(option => <button key={option} onClick={() => { setSort(option); setSortOpen(false); }} className="block w-full rounded px-3 py-2 text-left text-xs font-bold hover:bg-[hsl(var(--muted))]" data-testid={`button-sort-${option.toLowerCase()}`}>{option}</button>)}</div>}</div></div><div className="mt-4 flex items-center justify-between"><div><p className="font-display text-3xl font-black uppercase">Athlete Hub <span className="text-[hsl(var(--primary))]">Leaderboard</span></p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]">{activeTab} · sorted by {sort} · mock data</p></div><Trophy className="text-[hsl(var(--accent))]" size={25} /></div><div className="animate-stagger mt-5 grid gap-2">{leaderboard.map(entry => <LeaderboardRow key={entry.rank} entry={entry} />)}</div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--secondary))] p-6 text-[hsl(var(--secondary-foreground))] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--accent))]">Keep moving</p><h2 className="mt-2 font-display text-4xl font-black uppercase">Your spot is<br /><span className="text-[hsl(var(--primary))]">just the start.</span></h2></div><Sparkles className="text-[hsl(var(--secondary-accent))]" size={23} /></div><p className="mt-4 max-w-md text-sm leading-relaxed text-white/60">Play, log your work, and let your progress tell the story. The real competitive layer is coming soon.</p><Link href="/dashboard" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[hsl(var(--primary))]">Back to your hub <ArrowRight size={16} /></Link></div><div className="surface-elevated rounded-2xl border border-[hsl(var(--border))] p-6 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Your preview card</p><div className="mt-4 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[linear-gradient(145deg,hsl(var(--primary)),hsl(var(--secondary-accent)))] font-display text-2xl font-black text-[hsl(var(--primary-foreground))]">#4</div><div><p className="font-display text-3xl font-black uppercase">{player.firstName}</p><p className="font-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{player.position} · {player.ovr} OVR · Level {player.level}</p></div></div><Button variant="outline" className="mt-6 w-full" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} data-testid="button-back-top">View full ranking <ArrowRight size={15} /></Button></div></section>
  </div></div></AppShell>;
}